// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeAj1tB8BZghW-XvbGyUlHDH6G6mElyk',
    appId: '1:450092605249:web:a3ef0a1428d2346d5a0bc0',
    messagingSenderId: '450092605249',
    projectId: 'bazic-d9ad7',
    authDomain: 'bazic-d9ad7.firebaseapp.com',
    storageBucket: 'bazic-d9ad7.firebasestorage.app',
    measurementId: 'G-BGSMFLKE1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-gKPtukj02sDdvhxo-fNnXBHwCEYkoY',
    appId: '1:450092605249:android:e462dcff08e47ca85a0bc0',
    messagingSenderId: '450092605249',
    projectId: 'bazic-d9ad7',
    storageBucket: 'bazic-d9ad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEG2B-VTP88FtAloV56cVMElUakrGF0c',
    appId: '1:450092605249:ios:f1d3167839a737155a0bc0',
    messagingSenderId: '450092605249',
    projectId: 'bazic-d9ad7',
    storageBucket: 'bazic-d9ad7.firebasestorage.app',
    iosClientId: '450092605249-o0nlpkiot7t8mlpatiauss38rrnad780.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACEG2B-VTP88FtAloV56cVMElUakrGF0c',
    appId: '1:450092605249:ios:f1d3167839a737155a0bc0',
    messagingSenderId: '450092605249',
    projectId: 'bazic-d9ad7',
    storageBucket: 'bazic-d9ad7.firebasestorage.app',
    iosClientId: '450092605249-o0nlpkiot7t8mlpatiauss38rrnad780.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYeAj1tB8BZghW-XvbGyUlHDH6G6mElyk',
    appId: '1:450092605249:web:6bd82dc74cbf63005a0bc0',
    messagingSenderId: '450092605249',
    projectId: 'bazic-d9ad7',
    authDomain: 'bazic-d9ad7.firebaseapp.com',
    storageBucket: 'bazic-d9ad7.firebasestorage.app',
    measurementId: 'G-7510JJ776Z',
  );
}
